const Data = {
    products: [
        {
            _id:'1',
            name:'First Product',
            category: 'Electronic',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Second Product',
            category: 'Electronic',
            image:'/images/p2.jpg',
            price:80,countInStock:20,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Third Product',
            category: 'Electronic',
            image:'/images/p3.jpg',
            price:110, countInStock:0,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Fourth Product',
            category: 'Electronic',
            image:'/images/p4.jpg',
            price:599,countInStock:5,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Fifth Product',
            category: 'Electronic',
            image:'/images/p1.jpg',
            price:399,countInStock:15,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Sixth Product',
            category: 'Electronic',
            image:'/images/p6.jpg',
            price:100,
            brand:'Unknown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default Data;